# syntax=docker/dockerfile:1
# clean base image containing only comfyui, comfy-cli and comfyui-manager
FROM runpod/worker-comfyui:5.10.0-base

# build-time tokens for gated downloads are read from BuildKit secret
# mounts — they are never written to a layer or to image history.
# pass via: docker buildx build --secret id=hf_token,env=HF_TOKEN --secret id=civitai_api_key,env=CIVITAI_API_KEY .

# install custom nodes into comfyui
RUN git clone https://github.com/darksidewalker/ComfyUI-DaSiWa-Nodes /comfyui/custom_nodes/ComfyUI-DaSiWa-Nodes && cd /comfyui/custom_nodes/ComfyUI-DaSiWa-Nodes && (git checkout 03e8dde277da64acb3c5802ee58ba3a53e4640c9 2>/dev/null || (git fetch origin 03e8dde277da64acb3c5802ee58ba3a53e4640c9 --depth=1 && git checkout 03e8dde277da64acb3c5802ee58ba3a53e4640c9) || echo "WARN: commit 03e8dde277da64acb3c5802ee58ba3a53e4640c9 unreachable in https://github.com/darksidewalker/ComfyUI-DaSiWa-Nodes, falling back to default branch HEAD")
RUN git clone https://github.com/rgthree/rgthree-comfy /comfyui/custom_nodes/rgthree-comfy && cd /comfyui/custom_nodes/rgthree-comfy && (git checkout 2c5342a8cb0eaecaabf61435a5f37dd594c510ba 2>/dev/null || (git fetch origin 2c5342a8cb0eaecaabf61435a5f37dd594c510ba --depth=1 && git checkout 2c5342a8cb0eaecaabf61435a5f37dd594c510ba) || echo "WARN: commit 2c5342a8cb0eaecaabf61435a5f37dd594c510ba unreachable in https://github.com/rgthree/rgthree-comfy, falling back to default branch HEAD")
RUN comfy node install --exit-on-fail comfyui-kjnodes@1.2.6 --mode remote || (echo "WARN: comfyui-kjnodes@1.2.6 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-kjnodes --mode remote)

# download models into comfyui
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/Kim2091/2x-AnimeSharpV4/resolve/main/2x-AnimeSharpV4_RCAN.safetensors' --relative-path models/Unknown --filename '2x-AnimeSharpV4_RCAN.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/seraphimzz/checkpoints/resolve/7a24cf631edcc2db87963d364f6ab80e6dc2fc5d/dasiwaAnima_obsidianArchivesV2.safetensors' --relative-path models/Unknown --filename 'dasiwaAnima_obsidianArchivesV2_2915185.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/circlestone-labs/Anima/resolve/main/split_files/text_encoders/qwen_3_06b_base.safetensors' --relative-path models/Unknown --filename 'qwen_3_06b_base.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors' --relative-path models/Unknown --filename 'qwen_image_vae.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/keko24/qwen3-600M-autoround/resolve/main/model.safetensors' --relative-path models/text_encoders --filename 'qwen_3_600m.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors' --relative-path models/vae --filename 'QwenImage/qwen_image_vae.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=civitai_api_key BACKOFFS="60 300 900 1800 3600" && for i in 1 2 3 4 5; do CIVITAI_API_KEY="$(cat /run/secrets/civitai_api_key 2>/dev/null || true)" comfy model download --url 'https://civitai.com/api/download/models/3036240?fileId=3018440' --relative-path models/diffusion_models --filename 'Anima/DaSiWa-ANIMA-ObsidianArchives-v2_int8_row-wise_convrot_runtime.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done

# copy all input data (like images or videos) into comfyui (uncomment and adjust if needed)
# COPY input/ /comfyui/input/

# user-provided inputs override the auto-generated placeholders above.
RUN wget --progress=dot:giga -O '/comfyui/input/10638.png' "https://cool-anteater-319.convex.cloud/api/storage/2b18e883-472c-4fe3-9356-9951d21c7397"
